Feature/template files
nationalarchives/tna-research-redesign pull request #2
Opened 2017-05-25 15:50 UTC by netdesignr

Hi @domingobishop,

Can you please review this pull request?

Thank you!

Mihai

2017-05-30 09:36 UTC, domjngo requested changes
Please look at the comments

2017-05-30 09:36 UTC, domjngo commented on css/sass/main.scss
> +.page-template-page-section-landing {
Remove if not in use

2017-05-30 09:36 UTC, domjngo commented on css/sass/main.scss
> +p {
When using rules to override global rules, please use a new class to target these elements.
eg .page-template-class p { margin-bottom:0; }

2017-05-30 09:36 UTC, domjngo commented on page-research-repository-landing.php
> +                                 style="background-image: url('<?php echo preg_replace('/https?:\/\/research.(live|dev|test)lb\.nationalarchives\.gov\.uk\//', '/', $feat_image); ?>')">
The preg_replace should be inside the function

2017-05-30 09:36 UTC, domjngo commented on page-research-repository-landing.php
> +                                 style="background-image: url('<?php echo preg_replace('/https?:\/\/research.(live|dev|test)lb\.nationalarchives\.gov\.uk\//', '/', $feat_image); ?>')">
Actually, this should return a relative path. Try using make_path_relative function.

2017-05-30 09:36 UTC, domingobishop commented on page-research-repository-details.php
> +                                <span class="entry-meta">
Is there a reason why this content (.entry-meta) is a smaller font size?

2017-05-30 09:36 UTC, domingobishop commented on page-research-repository-landing.php
> +                                 style="background-image: url('<?php echo preg_replace('/https?:\/\/research.(live|dev|test)lb\.nationalarchives\.gov\.uk\//', '/', $feat_image); ?>')">
Background image needs CSS to position and size.

2017-05-30 09:36 UTC, domingobishop commented on page-research-repository-landing.php
> +                    <div class="col-xs-12 col-md-12 secondary-content">
col-xs-12 col-md-12 is not needed here

2017-05-30 09:36 UTC, domingobishop commented on page-research-repository-landing.php
> +                                    <?php the_excerpt(); ?>
If the excerpt is too long it's displaying [...]

2017-05-30 09:36 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_authors()
If data doesn't exist should this still return something?

2017-05-30 09:36 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_date_of_publication()
If data doesn't exist should this still return something?

2017-05-30 09:36 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_keywords_taxonomy()
If data doesn't exist should this still return something?

2017-05-30 09:36 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_published_by()
If data doesn't exist should this still return something?

2017-05-30 09:36 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_file_url_file_size()
If data doesn't exist should this still return something?

2017-05-31 16:35 UTC, punalsc commented on page-research-repository-landing.php
> +                    <div class="col-xs-12 col-md-12 secondary-content">
Done.

2017-05-31 16:57 UTC, punalsc commented on page-research-repository-landing.php
> +                                 style="background-image: url('<?php echo preg_replace('/https?:\/\/research.(live|dev|test)lb\.nationalarchives\.gov\.uk\//', '/', $feat_image); ?>')">
CSS background position and size DONE.

2017-05-31 16:58 UTC, punalsc commented on css/sass/main.scss
> +p {
Done.

2017-06-01 09:47 UTC, punalsc commented on page-research-repository-landing.php
> +                                 style="background-image: url('<?php echo preg_replace('/https?:\/\/research.(live|dev|test)lb\.nationalarchives\.gov\.uk\//', '/', $feat_image); ?>')">
Now using make_path_relative().

2017-06-02 10:10 UTC, domingobishop commented on page-research-repository-landing.php
> +                                    <?php the_excerpt(); ?>
To be reviewed at tna-base level

2017-06-02 10:13 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_authors()
Fixed

2017-06-02 10:13 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_date_of_publication()
Fixed

2017-06-02 10:13 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_keywords_taxonomy()
Fixed

2017-06-02 10:13 UTC, domingobishop commented on inc/functions/functions-templates.php
> +function display_published_by()
Fixed

2017-06-02 10:16 UTC, domjngo approved these changes

2017-06-02 10:16 UTC, merged